version: '3.9'
services:
  postgres:
    image: postgres
    container_name: s_transactions_db
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
    ports:
      - ${DB_PORT}:5432
